import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Koru Fest</title>
        <meta name="description" content="Generated by Kafeina" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.bgWide}>
          <Image
            src="https://res.cloudinary.com/afximagesection/image/upload/v1668123815/Kor%C3%BA_Fest_-_Afiche_web_wulel6.png"
            alt="advertisemente widescreen"
            width={1920}
            height={2203}
          />
        </div>

        <div className={styles.bgMovil}>
          <Image
            src="https://res.cloudinary.com/afximagesection/image/upload/v1668123815/Kor%C3%BA_Fest_-_Afiche_m%C3%B3vil_u5w1ik.png"
            alt="advertisemente movil"
            width={1081}
            height={2330}
          />
        </div>
      </main>
    </div>
  );
}
