import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Koru Fest</title>
        <meta name="description" content="Generated by Kafeina" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.bgWide}>
          <Image
            src="https://res.cloudinary.com/afximagesection/image/upload/v1666549775/Koru_web_design_kv7v5j.jpg"
            alt="advertisemente widescreen"
            width={1920}
            height={2203}
          />
        </div>

        <div className={styles.bgMovil}>
          <Image
            src="https://res.cloudinary.com/afximagesection/image/upload/v1666551400/Koru_web_design_movil_Mesa_de_trabajo_1_copia_yowchl.jpg"
            alt="advertisemente movil"
            width={1081}
            height={2330}
          />
        </div>
      </main>
    </div>
  );
}
